module.exports = {
    UNAUTHORIZED:'Unathorized Access',
    INTERNAL_SERVER_ERROR:'Internal server error.',
    REQUIRED_DATA:'Please fill all required data.',
    SUCCESSFULLY_DONE:'Data found successfully.',
    SUCCESSFULLY_UPDATE:'Data updated successfully.',
    WENT_WRONG:'Something went wrong',
    SAVED_SUCCESSFULLY:" is saved successfully.",
     ALL_READY_EXIST_EMAIL:'This email is Already exist.',
     NOT_MATCH:"Emailid does not exist.",
     LOGIN_SUCCESS:"Login successfully.",
     NOT_FOUND:"No data found.",
     UPDATE:"is updated successfully.",
     DELETE:"deleted successfully.",
     ALL_READY_EXIST_REGISTRATION_NO:"This registration number is already exists.",
    CORRECT_EMAIL:'Please send correct Email.',
    EMAIL_IS_REQ :'Email is required.',
    NAME_IS_REQ : 'Name is required.',
    ADMIN_PASS_REQ : 'Admin password is required.',
    ADMIN_EMAIL_REQ : 'Admin email is required.',
    CORRECT_ADMIN_EMAIL:'Please send correct admin email.',
    ORG_ADD_SUCCESS : 'Organisation added succesfully.',
    IMG_REQUIRED:'Image is required.',
    IMG_ADD_SUCCESS:'Image uploaded successfully.',
    ADMIN_ID_REQUIRED:'Admin id is required.',
    ORG_ID_REQUIRED:'Organisation id is required.',
    ADMIN_ID_INCORRECT:'Admin id is incorrect.',
    OLD_PASSWORD_INCORRECT:'Old password is incorrect.',
    NEW_CONFIRM_INCORRECT:'New and confirm password are not similar.',
    PASSWORD_UPDATE_SUCCESS:"Your password updated successfully.",
    CHOOSE_DIFFERENT_PASSWORD:"CHOOSE DIFFERENT PASSWORD",
    MAIL_SENT:"MAIL SENT",
    INCORRECT_PASSWORD:"INCORRECT PASSWORD",
    PARAMETER_IS_MISSING:"PARAMETER IS MISSING",
    NOTHING_TO_SELECT:"NOTHING_TO_SELECT",
    LIST_OF_MERCHANT:'LIST_OF_MERCHANT',
    merchant_registered_successfully:"MERCHANT REGISTERED SUCCESSFULLY",
    PENDING_LIST_OF_MERCHANT:"PENDING_LIST_OF_MERCHANT",
    BANNER_ADDED:"BANNER_ADDED",
    MERCHANT_ADDED_SUCCESSFULLY:"MERCHANT_ADDED_SUCCESSFULLY",
    MERCHANT_ACTIVATED:"MERCHANT_STATUS_ACTIVATED",
    LIST_OF_BANNER:"LIST_OF_BANNER",
    MERCHANT_EDIT_SUCCESSFULLY:"MERCHANT_EDIT_SUCCESSFULLY",
    MERCHANT_BLOCKED:"MERCHANT_BLOCKED",
    MERCHANT_DELETED:"MERCHANT_DELETED",
    LIST_OF_SUBADMIN:"LIST_OF_SUBADMIN",
    LOGOUT_SUCCESSFULLY:"LOGOUT_SUCCESSFULLY"
    
 };