/** 
 * @description All the Error messages that needed to be sent to Admin or App
 * @type {Object}
*/
module.exports.ErrorMessage = Object.freeze({
    INVALID_TOKEN: 'Unauthorized user.',
    INTERNAL_ERROR: 'Internal Server Error.',
    INVALID_CREDENTIAL: 'Invalid credentials.',
    SOMETHING_WRONG: 'Unexpected error!',
    NO_TOKEN: 'Please provide token.',
    EMAIL_NOT_REGISTERED: 'Provided email is not registered.',
    NOT_REGISTERED: "Provided email/mobile number is not registered.",
    RESET_PASSWORD_EXPIRED: 'Your Token has expired.',
    WRONG_PASSWORD: 'Please enter valid password.',
    INVALID_MOBILE: 'This mobile number is not valid.',
    EMAIL_EXIST: 'This email already exists.',
    NOT_FOUND: 'Requested data not found.',
    USER_NOT_FOUND: 'This user does not exist.',
    UPDATE_NOT: "Unexpected error during update, please try again.",
    MOBILE_EXIST: 'This mobile number already exists.',
    USERNAME_EXIST: 'This user name already exists.',
    ALREADY_EXIST: 'Email/Mobile number already exists.',
    USER_ID: 'A valid User Id is required.',
    BLOCKED_BY_ADMIN: 'You are not authorized, please contact Admin.',
    DELETED_BY_ADMIN: 'Your account is deleted, please contact Admin.',
    FIELD_REQUIRED: 'Fields are required.',
    OLD_PASSWORD: 'You have provided an incorrect old password.',
    INCORRECT_JWT: 'Invalid JWT token.',
    FORBIDDEN: 'There was an error in sending email.',
    INVALID_OTP: 'Invalid OTP',
    OTP_EXPIRED: "OTP has expired, please try resend OTP.",
    CATEGORY_EXISTS: "This category already exists.",
    EPISODE_EXISTS: "This episode already exists.",
    VIDEO_EXISTS: "This video already exists.",
    AUDIO_EXISTS: "This audio already exists.",
    SUBJECT_EXISTS: "This subject name already exists.",
    TIME_EXISTS: "This time has already been appointed for other event.",
    KEY_PROVIDE: "Please provide a key.",
    PLAN_TAKEN: "This plan is already taken by you.",
    PLAN_EXPIRED: "Your membership has been expired. Please renew it by selecting subscription on Setting screen.",
    PLAN_PURCHASE: "You cannot use FREE TRIAL again. Please purchase other plan.",
    SUBSCRIPTION_EXISTS: "This subscription already exists.",
    PLAN_NOT_CHOSEN: "You have not yet chosen any plan."

});

/** 
 * @description All the Success messages that needed to be sent to App or Admin
 * @type {Object}
*/
module.exports.SuccessMessage = Object.freeze({
    SIGNUP_SUCCESSFULLY: "Thanks, You have successfully signed up.",
    LOGIN_SUCCESS: 'Your login is successful.',
    FORGET_SUCCESS: 'A password link has been sent to your registered ID.',
    RESET_SUCCESS: 'Your password was successfully changed.',
    PRODUCT_LIST_FETCH: 'Successfully fetched product list.',
    USER_LIST_FETCH: 'Successfully fetched user list.',
    AUTHORIZATION: 'This User is Authorized.',
    ACCOUNT_CREATION: 'Your account has been created successfully.',
    EMAIL_SEND: "Otp has been sent to your registered Email successfully.",
    OTP_SEND: 'Otp has been sent to your registered mobile number.',
    VERIFY_OTP: 'OTP verified successfully.',
    PIN_SET: "Your Pin has been set successfully.",
    PASSWORD_UPDATE: "Your password was updated successfully.",
    DATA_SAVED: "Data is saved successfully.",
    DETAIL_GET: "Details have been fetched successfully.",
    DATA_FOUND: "Requested data found",
    PROFILE_DETAILS: "Your profile detail was updated sucessfully.",
    STATUS_UPDATED: "Your Status has been changed successfully.",
    UPDATE_SUCCESS: "Successfully updated.",
    BLOCK_SUCCESS: "Successfully blocked.",
    UNBLOCK_SUCCESS: "Successfully activated.",
    DELETE_SUCCESS: "Successfully deleted.",
    SUB_ADMIN_CREATED: "Sub-admin was created successfully.",
    CARD_ADD: "Card details has been added successfully.",
    PLAN_ADD: "Membership plan has been added successfully.",
    CATEGORY_ADD: "Category has been added successfully.",
    EPISODE_ADD: "Episode has been added successfully.",
    VIDEO_ADD: "Video has been added successfully.",
    AUDIO_ADD: "Audio has been added successfully.",
    MEMBER_ADD: "Member has been added successfully.",
    SUBSCRIPTION_ADD: "Subscription has been added successfully.",
    MENTAL_HEALTH_ADD: "Mental health campaign has been added successfully",
    MEDICAL_ADD: "Medical condition knowledge has been added successfully.",
    FAVOURITE_HEALTH: "Mental health campaign has been favourited successfully.",
    SCHEDULER_ADD: "Schedular has been added successfully.",
    SCHEDULE_COMPLETE: "Schedule has been completed successfully.",
    FEEDBACK_ADD: "Feedback has been added successfully.",
    SMS_SEND: "The SMS has been send to the buddies successfully.",
    MOOD_ADD: "Mood added successfully.",
    BUDDIES_ADD: "Buddies has been added successfully.",
    TRANSACTION_SUCCESS: "Transaction has been done successfully",
    MESSAGE_SEND: "Message has been send successfully",
    COMPANY_USERS_ADD: "Company users have been added successfully.",
    LOGOUT_SUCCESS: "Logged out successfully",
    DATA_OK: "OK. You can proceed further."
});