const express = require('express')
const router=express.Router()
const vendorController = require ("../controller/vendorController")

router.post('/login',vendorController.vendorLogin)
router.post('/forgotpassword',vendorController.forgotPassword)
router.post('/changepassword',vendorController.changePassword)
router.post('/resetPassword',vendorController.resetPassword)
router.post('/showProfile',vendorController.showProfile)
router.post('/editProfile',vendorController.editProfile)
router.post('/acceptAddMoney',vendorController.acceptAddMoney)
router.post('/acceptWithdrawMoney',vendorController.acceptWithdrawMoney)
router.post('/acceptSendMoney',vendorController.acceptSendMoney)
router.post('/rejectRequest',vendorController.rejectRequest)
router.post('/viewAddMoneyRequests',vendorController.viewAddMoneyRequests)
router.post('/viewWithdrawMoneyRequests',vendorController.viewWithdrawMoneyRequests)
router.post('/viewSendMoneyRequests',vendorController.viewSendMoneyRequests)
router.post('/viewParticularRequests',vendorController.viewParticularRequests)
module.exports=router